### ISSUE TITLE
Support one-to-many relationships

### ISSUE THREAD

**Issue by rexxars** [vaffel/sql-to-graphql#10]
We currently support one-to-one, but we should definitely also support one-to-many.

**Comment by kbrabrand** [comment]
I have been thinking about this. I'll see if I can make something within the next week or so.

**Comment by rexxars** [comment]
:+1: This would be a great addition

**Comment by rexxars** [comment]
Did you get anywhere with this?

I think this should work:
```sql
SELECT COUNT(`potential_column`) AS `hasSameValues`
FROM `someTable`
GROUP BY `potential_column`
HAVING `hasSameValues` > 1
LIMIT 1;
```

Currently we find all columns which matches the name of some other table (eg, `forum_id` from a `threads` table, assume it's a reference to the primary key within `forums` table).

If we in this step run the query to find out if there are duplicate values, then we should be able to assume that going the other way (`forum` => `threads` in this case) is going to be a valid one-to-many connection.

I'll start implementing this, unless you already have something in progress?

**Comment by kbrabrand** [comment]
I got as far as writing that query, but no more than that.. 😔 It derailed when I took down a server doing a dump

**Comment by rexxars** [comment]
Haha, alright. I'll take a look :-)
