### ISSUE TITLE
Question - GraphQL playground using generated schema

### ISSUE THREAD

**Issue by michshat** [vaffel/sql-to-graphql#34]
Awesome work!!!

Quick question, I used mysql sakila database to output Country and City tables, using following parameters (on Windows):
`> sql2graphql --db sakila -r true -h localhost -u root -p test -t city -t country --output-dir C:\Development\Playground\app`

Got this schema generated:
````
type City implements Node {
  id: ID!
  city: String!
  countryId: Int!
  country: Country
  lastUpdate: Int!
}

type Country implements Node {
  id: ID!
  country: String!
  lastUpdate: Int!
}

interface Node {
  id: ID!
}

type RootQueryType {
  node(id: ID!): Node
}
````

can't seem to query sever data on `http//localhost:3000` ... tried many scenarious, but keep in running into `Cannot query field "City" on "RootQueryType".`  error.

Do I need to modify schema.js to nest Country and City types under RootQueryType?

**Comment by rexxars** [comment]
It looks like you've generate the app using the `--relay` option.

In Relay, instead of having root-level queries for each individual type, you have a single field: `node` that takes an ID.

So in your case, you'd query it like this:

```
{
  node(id: "Q2l0eToxOA==") {
    id,
    ... on City {
      city,
      countryId
    }
  }
}
```

**Comment by rexxars** [comment]
If you generate the same application without the `--relay` option, you should be able to query it using:

```
{
  City(id: 18) {
    id,
    city,
    countryId
  }
}
```

**Comment by michshat** [comment]
@rexxars Thanks!!! Just tried it with --relay option on and without - Works great!

Thanks again!
