### ISSUE TITLE
Add Support Many-To-One (n:1) relationship mappings?

### ISSUE THREAD

**Issue by michshat** [vaffel/sql-to-graphql#35]
Example `City` to `Country`

**Comment by rexxars** [comment]
This is already supported in the latest version (>= 2), actually :-) 

Just run a new `npm install -g sql-to-graphql` and regenerate the app. Depends on the naming convention mentioned in the readme.

**Comment by michshat** [comment]
That's just incredible. Thanks a lot!!!
